# Generated by Django 4.1.7 on 2023-04-03 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_genre_alter_book_summry_alter_genre_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 4, 11, 1, 36, 24, 439447), help_text='Default one week (7days).'),
        ),
    ]
