# Generated by Django 4.1.7 on 2023-04-25 14:56

import book.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0006_alter_bookinstance_due_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(default=book.models.BookInstance.default_user, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 18, 26, 38, 993270), help_text='Default one week (7days).'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('o', 'On Loan'), ('a', 'Available')], default='a', help_text='Book Availability', max_length=1),
        ),
    ]
