# Generated by Django 4.1.7 on 2023-05-16 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_bookinstance_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 5, 23, 13, 18, 19, 494217), help_text='Default one week (7days).'),
        ),
    ]
