# Generated by Django 4.1.7 on 2023-05-16 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookinstance_due_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='status',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 5, 23, 13, 29, 8, 446503), help_text='Default one week (7days).'),
        ),
    ]
