# Generated by Django 4.2.1 on 2023-05-21 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_bookinstance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('o', 'On Loan'), ('a', 'Available')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('o', 'On Loan'), ('a', 'Available')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 18, 33, 48, 556322), help_text='Default one week (7days).'),
        ),
    ]
