# Generated by Django 4.2.1 on 2023-05-21 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_status_bookinstance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 18, 35, 25, 652254), help_text='Default one week (7days).'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('o', 'On Loan'), ('a', 'Available')], default='o', max_length=1),
        ),
    ]
