# Generated by Django 4.2.1 on 2023-05-22 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_bookinstance_due_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 19, 33, 51, 898730), help_text='Default one week (7days).'),
        ),
    ]
