# Generated by Django 4.2.1 on 2023-06-09 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_bookinstance_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 6, 16, 21, 38, 55, 444644), help_text='Default one week (7days).'),
        ),
    ]
