# Generated by Django 4.2.1 on 2023-06-28 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_bookinstance_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(blank=True, null=True, upload_to='bookImage/'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 13, 15, 40, 303178), help_text='Default one week (7days).'),
        ),
    ]
